name: Create Agent Release
on:
  workflow_run:
    workflows: [Build and Push Platform Image]
    types: [completed]
    branches: [cifar10/dev]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Build Service
        working-directory: ./src/service
        run: python setup.py sdist bdist_wheel

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Release Sower Agent"
          files: |
            ./src/service/dist/*
